views/auth.py
from flask import Blueprint, render_template, session, redirect, url_for, request, flash

import auth
import forms
from service.user_service import UserService

auth_bp = Blueprint('auth', __name__)

@auth_bp.route('/signin', methods=['GET', 'POST'])
def sign_in():
    form = forms.SignInForm(request.form)
    if request.method == 'POST' and form.validate():
        user = UserService.verify(email=request.form['email'], password=request.form['password'])
        if user:
            session['authenticated'] = 1
            session['user_id'] = user['id']
            session['email'] = user['email']
            session['phone'] = user['phone']
            session['firstname'] = user['firstname']
            session['lastname'] = user['lastname']
            session['activated'] = user['activated']
            session['role'] = user['title']
            return redirect(url_for('homepage.index'))
        else:
            flash('Incorrect login or password')
    return render_template("auth/sign_in.html", form=form)

@auth_bp.route('/signup', methods=['GET', 'POST'])
def sign_up():
    form = forms.RegistrationUserForm(request.form)
    if request.method == 'POST' and form.validate():
        insertedId = UserService.register(email=request.form['email'], password=request.form['password'], phone=request.form['phone'], firstname=request.form['firstname'], lastname=request.form['lastname'])
        if insertedId != -1:
            return redirect(url_for('auth.sign_in'))
        else:
            flash('User with this email already exists')
    return render_template('auth/sign_up.html', form=form)

@auth_bp.route('/signout')
@auth.login_required
def signout():
    session.pop("authenticated")
    session.pop("user_id")
    session.pop("email")
    session.pop("phone")
    session.pop("firstname")
    session.pop("lastname")
    session.pop("activated")
    session.pop("role")
    return redirect(url_for('homepage.index'))

templates/about_us.html
{% extends 'main.html' %}
{% block content %}

<section class="flex-center" xmlns="http://www.w3.org/1999/html">

  <h1>How it works?</h1>

    <div class="bloky">
        <div class="step-block">
            <h2 class="block-title">Step 1</h2>
            <p>
                <h3>Create an account</h3> </br>
            <img class="block-img" src="static/img/1step.png" >
            </p>
        </div>
         <div class="step-block">
            <h2 class="block-title">Step 2</h2>
             <p>
                 <h3>Confirm your identity</h3> </br>
            <img class="block-img" src="static/img/2step.png" >
             </p>
        </div>
         <div class="step-block">
            <h2 class="block-title">Step 3</h2>
             <p>
                 <h3>Hand over the materials</h3> </br>
            <img class="block-img" src="static/img/3step.png" >
             </p>
        </div>
    </div>
</section>

{% endblock %}

templates/footer.html
<footer>

    <div>
      <h3>Fast links</h3>
   <ul>
   <li> <a href="{{url_for('homepage.index')}}">Home</a></li>
  <li>   <a href="{{url_for('view_all_stats')}}">Statistics</a></li>
   <li>  <a href="{{url_for('view_current_prices')}}"> Prices</a></li>
 <li> <a href="{{url_for('view_about_us')}}">About Us</a></li>

    {% if session['authenticated'] %}
        {% if session['role'] == 'default' %}
        <li>  <a href="{{url_for('account.history')}}">History</a>
        {% endif %}
   <li>  <a href="{{url_for('account.account')}}">Account</a></li>
    {% if session['role'] == 'admin'  %}

            <li>  <a href="{{url_for('worker.users.manage_accounts')}}">Approve Accounts</a></li>
            <li>  <a href="{{url_for('worker.collections.new_collection')}}">Register collection</a></li>
        <li>  <a href="{{url_for('worker.collections.update_collections')}}">All collections</a></li>
        <li>  <a href="{{url_for('admin.materials.update_prices')}}">Update Price</a></li>
        <li>  <a href="{{url_for('admin.accounts.manage_accounts')}}">Manage Accounts</a></li>

    {% endif %}
    {% if session['role'] == 'limited_admin'%}

        <li>  <a href="{{url_for('admin.materials.update_prices')}}">Update Price</a></li>
        <li>  <a href="{{url_for('admin.accounts.manage_accounts')}}">Manage Accounts</a></li>

    {% endif %}
        {% if session['role'] == 'employee'  %}

        <li>  <a href="{{url_for('worker.users.manage_accounts')}}">Approve Accounts</a></li>
        <li>  <a href="{{url_for('worker.collections.new_collection')}}">Register collections</a></li>
        <li>  <a href="{{url_for('worker.collections.update_collections')}}">All collections</a></li>

        {% endif %}

   <li>  <a href="{{url_for('auth.signout')}}">Logout</a></li>

    {% else %}
   <li>  <a href="{{url_for('auth.sign_in')}}">Sign in</a></li>
    {% endif %}
    </ul>
    </div>

    <div>
      <h3>Contact Info</h3>
        <address>
          PEF MENDELU<br>
          Zemědělská 1 <br>
          Brno, 613 00
        </address>
    </div>

</footer>

templates/main.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
  <title>Company name</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
  <script src="https://kit.fontawesome.com/381f47a1a9.js" crossorigin="anonymous"></script>

  <!-- Custom styles -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}" type="text/css">

  <style>
    @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap');
  </style>
</head>

<body>
  <!-- Include navigation -->
  {% include 'nav.html' %}

  <main>
    <!-- Flash messages -->
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class="flashes-box">
      <h3 class="flashes-title">
        Submitting the form failed due to the following
      </h3>

      <div class="flashes-content">
        <ul>
          {% for message in messages %}
          <li>{{ message }}</li>
          {% endfor %}
        </ul>
      </div>
    </div>
    {% endif %}
    {% endwith %}

    <!-- Render main content -->
    {% block content %}

    {% endblock %}
  </main>

  <!-- Include footer -->
  {% include 'footer.html' %}

  <!-- Scripts -->
  <script>
    // Format date
    const dateElements = document.querySelectorAll('[data-dateformatter="true"]');
    dateElements.forEach((element) => {
      const date = new Date(element.innerText);
      element.innerText = date.toLocaleString();
    });
  </script>

</body>

</html>

templates/nav.html
{% block nav %}
<div class="hamburger" onclick="document.getElementById('nav').classList.toggle('visible')">
    <i class="fa-solid fa-bars"></i>
</div>
<nav id="nav">
    <ul>
        <li> <a href="{{url_for('homepage.index')}}">Home</a></li>
        <li> <a href="{{url_for('view_all_stats')}}">Statistics</a></li>
        <li> <a href="{{url_for('view_current_prices')}}"> Prices</a></li>
        <li> <a href="{{url_for('view_about_us')}}">About Us</a></li>

        {% if session['authenticated'] %}
        {% if session['role'] == 'default' %}
        <li> <a href="{{url_for('account.history')}}">History</a>
            {% endif %}
        <li> <a href="{{url_for('account.account')}}">Account</a>
            {% if session['role'] == 'admin' %}
            <ul>
                <li> <a href="{{url_for('worker.users.manage_accounts')}}">Approve Accounts</a></li>
                <li> <a href="{{url_for('worker.collections.new_collection')}}">Register collection</a></li>
                <li> <a href="{{url_for('worker.collections.update_collections')}}">All collections</a></li>
                <li> <a href="{{url_for('admin.materials.update_prices')}}">Update Price</a></li>
                <li> <a href="{{url_for('admin.accounts.manage_accounts')}}">Manage Accounts</a></li>
            </ul>
            {% endif %}
            {% if session['role'] == 'limited_admin'%}
            <ul>
                <li> <a href="{{url_for('admin.materials.update_prices')}}">Update Price</a></li>
                <li> <a href="{{url_for('admin.accounts.manage_accounts')}}">Manage Accounts</a></li>
            </ul>
            {% endif %}
            {% if session['role'] == 'employee' %}
            <ul>
                <li> <a href="{{url_for('worker.users.manage_accounts')}}">Approve Accounts</a></li>
                <li> <a href="{{url_for('worker.collections.new_collection')}}">Register collections</a></li>
                <li> <a href="{{url_for('worker.collections.update_collections')}}">All collections</a></li>
            </ul>
            {% endif %}
        </li>
        <li> <a href="{{url_for('auth.signout')}}">Logout</a></li>

        {% else %}
        <li> <a href="{{url_for('auth.sign_in')}}">Sign in</a></li>
        {% endif %}
    </ul>
</nav>
{% endblock%}

templates/prices.html
{% extends 'main.html' %}

{% block content %}
<section class="flex-center">
  <h1>Current Prices</h1>

  <div class="responsive-table">
    <table>
      <thead>
        <tr>
          <th>Material</th>
          <th>Price</th>
          <th class="column-right-align">Last Updated</th>
        </tr>
      </thead>

      <tbody>
        {% for material in prices %}
        <tr>
          <td>{{ material.name }}</td>
          <td>{{ "%.2f"|format(material.price) }} Kč</td>
          <td class="column-right-align" title="{{ material.added }}" data-dateformatter="true">{{ material.added }}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

</section>
{% endblock %}

templates/stats.html
{% extends 'main.html' %}

{% block content %}
<section class="flex-center">
  <h1>Statistics</h1>

  <div class="responsive-table only-mobile">
    <table>
      <thead>
        <tr>
          <th></th>
          {% for record in stats %}
          <th>{{ record.name }}</th>
          {% endfor %}
        </tr>
      </thead>

      <tbody class="stacked-column-left">
        <tr>
          <td>Total Weight</td>
          {% for record in stats %}
          <td>{{ "%.2f"|format(record.total_received) }} kg</td>
          {% endfor %}
        </tr>
        <tr>
          <td>Total Received</td>
          {% for record in stats %}
          <td>{{ record.total_received_count }}x</td>
          {% endfor %}
        </tr>
        <tr>
          <td>Average Received Weight</td>
          {% for record in stats %}
          <td>{{ "%.2f"|format(record.average_weight) }} kg</td>
          {% endfor %}
        </tr>
        <tr>
          <td>Last Received</td>
          {% for record in stats %}
          <td title="{{ record.latest_received }}" data-dateformatter="true">{{ record.latest_received }}</td>
          {% endfor %}
        </tr>
      </tbody>
    </table>
  </div>

  <div class="responsive-table only-desktop">
    <table>
      <thead>
        <tr>
          <th>Material</th>
          <th>Total Weight</th>
          <th>Total Received</th>
          <th>Average Received Weight</th>
          <th class="column-right-align">Last Received</th>
        </tr>
      </thead>
      <tbody>

        {% for record in stats %}
        <tr>
          <td>{{ record.name }}</td>
          <td>{{ "%.2f"|format(record.total_received) }} kg</td>
          <td>{{ record.total_received_count }}x</td>
          <td>{{ "%.2f"|format(record.average_weight) }} kg</td>
          <td class="column-right-align" title="{{ record.latest_received }}" data-dateformatter="true">{{
            record.latest_received }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

</section>
{% endblock %}